version: '2.3'
services:
    jupyter_notebook:
        build: ./deep_learning/
        shm_size: '8gb'
        runtime: nvidia
        ports:
          - "8888:8888"
          - "5000:5000"
          - "8097:8097"
        expose:
            - "8888"
            - "27017"
            - "80"
            - "6379"
            - "8080"
            - "5000"
            - "8097"
        volumes:
            #- /home/dxdo-employee/:/home/user/
            - /media/shirkin39/DATA1:/home/user/
            - /tmp/.X11-unix:/tmp/.X11-unix
            #xhost +local:docker in terminal before using
        networks:
          application-network:
              aliases:
              - jupyter.compose
        restart: on-failure
        environment:
        - PYTHONUNBUFFERED=0
        - DISPLAY=unix:1
        command : "jupyter lab --no-browser --allow-root --ip=0.0.0.0 --port=8888"

    #tensorboard:
    #    build : ./deep_learning/
    #    runtime: nvidia
    #    ports :
    #      - "6006:6006"
    #    expose:
    #      - "6006"
    #    volumes :
            #- /home/dxdo-employee/:/home/user/
    #        - /media/shirkin39/DATA1:/home/user/
    #        - /tmp/.X11-unix:/tmp/.X11-unix
    #    command : "tensorboard --logdir cosine_metric_learning/eval_output/"

networks:
    application-network:
        external: false
